
# target folder for ISE export tool to export to
# https://learn.microsoft.com/en-us/azure/logic-apps/export-from-ise-to-standard-logic-app
exported_ise_directory: "C:\\Weixian\\Projects\\IaC-for-GCC\\src\\tools\\ise-migration\\exported-ise"

logicapp_storage_accounts:

  # example of workflows uploading to 2 Logic App Standard (LAS) linking to same storage account with 2 different fileshare
  - storage_account:
      account_name: "logicappisemigrated1"
      sas_token_envvar_name: "logicapp_standard_sas_1"   # env variable name that stores storage account sas token
      fileshares:
       -  file_share_name: "logicapp-ise-migrated-16370d0"
          overwrite_workflow: false
          workflow_folder_names:
          - ise-logicapp-1
          - ise-logicapp-1.2
       -  file_share_name: "logic-standard-dev-39cf0"
          overwrite_workflow: true
          workflow_folder_names:
          - ise-logicapp-1.3

  # example of workflows uploading to another LAS linking to a separate storage account
  - storage_account:
      account_name: "logicappisemigrated2"
      sas_token_envvar_name: "logicapp_standard_sas_2"
      fileshares:
       -  file_share_name: "fileshare-logic-standard-dev-001"
          overwrite_workflow: true
          workflow_folder_names:
          - ise-logicapp-3
          - ise-logicapp-4


  