
exported_ise_directory: "C:\\Weixian\\Projects\\IaC-for-GCC\\src\\tools\\ise-migration\\exported-ise"

fileshare_workflow_map:
  - storage_Account_name: ""
    fileshareName: "fileshare-logic-standard-dev-001"
    sas_url_envvar_name: ""
    workflow_folder_names:
    - ise-logicapp-1
    - ise-logicapp-1.2
    - ise-logicapp-1.3

  - storage_Account_name: ""
    fileshareName: "fileshare-logic-standard-dev-002"
    sas_url_envvar_name: ""
    workflow_folder_names: [] # empty means upload all "remaining" workflows

# - fileshare_workflow_map:
#     fileshareName: "fileshare-logic-standard-dev-002"
#     sas_url_envvar_name: ""
#     workflow_folder_names:  # empty means upload all "remaining" workflows


  