
exported_ise_directory: "C:\\Weixian\\Projects\\IaC-for-GCC\\src\\tools\\ise-migration\\exported-ise"

logicapp_storage_accounts:
  - storage_account:
      account_name: "logicappisemigrated1"
      sas_token_envvar_name: "logicapp_standard_sas_1"   # env variable name that stores storage account sas token
      fileshares:
       -  file_share_name: "fileshare-logic-standard-dev-001"
          workflow_folder_names:
          - ise-logicapp-1
          - ise-logicapp-1.2
       -  file_share_name: "fileshare-logic-standard-dev-002"
          workflow_folder_names:
          - ise-logicapp-1.3

  - storage_account:
      account_name: "logicappisemigrated2"
      sas_token_envvar_name: "logicapp_standard_sas_1"
      fileshares:
       -  file_share_name: "fileshare-logic-standard-dev-001"
          workflow_folder_names:
          - ise-logicapp-3
          - ise-logicapp-4


  